### PR TITLE
 deleted/missing content fix

### LINKED ISSUE #2: Handle deleted content guids
As reported here:

https://community.rstudio.com/t/connect-api-deleted-content-issue/22245

### PR DESCRIPTION
**Pull request by jvail1**
Here's the deleted/missing content fix we discussed on the message boards.

close #2

### CODE REVIEW

**Comment by colearendt** [comment]
Thanks @jvail1 ! Looks good! It looks like your commits are disconnected from your GitHub ID? Do you have `git config` set to the appropriate email address? If you could fix that and force push, it will ensure that you get appropriate attribution!

**Comment by jvail1** [comment]
Okay thanks.  I made the updates.  It looks like my full name is displaying.  Thanks again!

**Comment by colearendt** [comment]
Would you like for me to go ahead and merge? It looks like it shows your full name, but it is not actually tied to your GitHub account for some reason. You can `git commit --amend` and `git push +branchname` to force an update, but I'm happy to merge if it's not important to you :smile: 

image

The grey images should have your same blue logo.

**Comment by jvail1** [comment]
Thanks Cole, I think it’s okay to merge without my github account being tied in.  Thanks for the heads up.

**Pull request merged**
